### ISSUE TITLE
Enjoyed your talk!

### ISSUE THREAD

**Issue by jcward** [jdonaldson/golgi#3]
Hey Justin, I enjoyed your talk. I appreciated the "let's just do one thing, and do it well" focus.

I played with golgi a bit, in light of [considering it](https://github.com/jcward/haxe-js-webstack/issues/2) for my experimental web stack. I first wanted to make a simple, one-hx-file test (as I often do) and ran into [this error](https://github.com/jdonaldson/golgi/blob/master/src/golgi/Build.hx#L271). Not a big deal, but I'm curious about the technical reason for this?

As far as "issue"... Hmm... well, you're not following me on Twitter, so I couldn't message you "great talk" there. That's an issue, I suppose. :laughing: Cheers!

**Comment by jdonaldson** [comment]
Hi Jeff, thanks for the kind words.

The explicit error state/message is there due to the fact that Haxe doesn't really have order-of-evaluation guarantees for macro code, and having two classes involved in a build macro can really throw some cryptic errors... it's possible to reference a child/dependent class before the parent has been completely resolved for instance.    Here's some relevant tidbits from the manual : https://haxe.org/manual/macro-limitations-build-order.html

I'm still working on this, and I might find a way around it, but for now the safest thing to do is  prevent macro-built classes from sharing modules with each other or their dependent types.

Also, as a heads up, I talked with NC and Juraj and will likely tweak the protocol a bit based on their suggestions.  It shouldn't be too drastic, and your code should still work after some simple and obvious fixes.

Stay tuned, and thanks for giving it a shot!
